//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urunn
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunTable
    {
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunResmi { get; set; }
        public string UrunAçıklaması { get; set; }
    }
}
